---
title: "medicare-exploration"
author: "XRZ"
date: '2023-07-28'
output: html_document
---

#Purpose:
This R markdown script visualizes things SQL can't do


# SECTION 0: Loading required packages, making connections, the usual

## 0.1 Load packages
```{r package-loading, warning = FALSE}
# Package installs/loading 

if (!require("pacman")) install.packages("pacman")
pacman::p_load(RPostgres, DBI, odbc, keyring, openxlsx, tidyverse, beepr, tictoc, here)

```

## 0.2 Connect to TACC
```{r connect-to-tacc}
#PREREQUISITE: Set up your username/password in Keyring
# Instructions: replace indicated areas in code below with your username/password for TACC server
# Run it once, and delete from code - code will not need to be run more than once per user per computer
# Keyring will save your username/password to your OS credential store, and the service/user/password combo
# can be retrieved without hardcoding a password or requring user input.
# key_set_with_value(service = "Greenplum", 
#                   username = "-----------", #replace with your username
#                   password = "-----------") #replace with your password

# Function for connecting to TACC/Greenplum
# TACC kicks you out for inactivity so just call function before connections
connect_to_tacc <- function() {
tac <- dbConnect(RPostgres::Postgres(),
	 dbname = "uthealth",
	 user = "xrzhang",
	 password = key_get("Greenplum", "xrzhang"),
	 host = "greenplum01.corral.tacc.utexas.edu",
	 port = 5432)
}

```

## 0.3 Connect to SPC
```{r connect-to-spcdedpwpvs1}
#PREREQUISITE: Set up connection to SPCDEDPWPVS1 in ODBC Data sources
#Make sure the default schema is correct! This one is set to medicaid

#Connect to SPCDEDPWPVS1
spc <- dbConnect(odbc::odbc(),
	 dsn = "medicaid")
```

## 0.4 Clear R environment (except for DB connections)
```{r clear-environment}
# clears R environment except for DB connections
rm(list=setdiff(ls(), c("tac", "spc", "connect_to_tacc")))
```

## 0.5 Declare root directory and set misc R options
```{r}
knitr::opts_chunk$set(echo=TRUE, rows.print=25)
options("scipen"=100, "digits" = 4) #avoid scientific notation
# here::i_am("prepare/penguins.R")
```


# SECTION 1: pull data from Greenplum

```{r}

tac = connect_to_tacc()

sql = "select clm_bene_pd_amt
  from medicare_national.bcarrier_claims_k
  where year = '2020' and clm_bene_pd_amt != '0.00';"

results = dbGetQuery(tac, sql)

```

```{r}

results_num = as.numeric(unlist(results))

results_filtered = results_num[results_num <= 100]

```
# SECTION 2: histogram it

```{r}
hist(results_filtered, breaks = 100)
axis(1, at = seq(0, 100, by = 5))

```






