drop table if exists medicare_national.carrier_base_enc;

create table medicare_national.carrier_base_enc
(
	year text,
	BENE_ID varchar,
	SAMPLE_GROUP varchar,
	ENC_JOIN_KEY varchar,
	CLM_TYPE_CD varchar,
	CLM_FROM_DT varchar,
	CLM_THRU_DT varchar,
	SRVC_MONTH varchar,
	CLM_CHRT_RVW_SW varchar,
	CLM_CNTL_NUM varchar,
	CLM_ORIG_CNTL_NUM varchar,
	CLM_FINL_ACTN_IND varchar,
	CLM_LTST_CLM_IND varchar,
	EDPS_CREATE_DT varchar,
	CLM_RCPT_DT varchar,
	CLM_FREQ_CD varchar,
	CNTRCT_NUM varchar,
	CNTRCT_PBP_NUM varchar,
	CLM_MDCL_REC varchar,
	ORG_NPI varchar,
	ORG_TXNMY_CD varchar,
	RFRG_PHYSN_NPI varchar,
	PRNCPAL_DGNS_CD varchar,
	PRNCPAL_DGNS_VRSN_CD varchar,
	ICD_DGNS_CD1 varchar,
	ICD_DGNS_VRSN_CD1 varchar,
	ICD_DGNS_CD2 varchar,
	ICD_DGNS_VRSN_CD2 varchar,
	ICD_DGNS_CD3 varchar,
	ICD_DGNS_VRSN_CD3 varchar,
	ICD_DGNS_CD4 varchar,
	ICD_DGNS_VRSN_CD4 varchar,
	ICD_DGNS_CD5 varchar,
	ICD_DGNS_VRSN_CD5 varchar,
	ICD_DGNS_CD6 varchar,
	ICD_DGNS_VRSN_CD6 varchar,
	ICD_DGNS_CD7 varchar,
	ICD_DGNS_VRSN_CD7 varchar,
	ICD_DGNS_CD8 varchar,
	ICD_DGNS_VRSN_CD8 varchar,
	ICD_DGNS_CD9 varchar,
	ICD_DGNS_VRSN_CD9 varchar,
	ICD_DGNS_CD10 varchar,
	ICD_DGNS_VRSN_CD10 varchar,
	ICD_DGNS_CD11 varchar,
	ICD_DGNS_VRSN_CD11 varchar,
	ICD_DGNS_CD12 varchar,
	ICD_DGNS_VRSN_CD12 varchar,
	ICD_DGNS_CD13 varchar,
	ICD_DGNS_VRSN_CD13 varchar,
	CLM_OBSLT_DT varchar,
	CLM_BPRVDR_CITY_NAME varchar,
	CLM_BPRVDR_USPS_STATE_CD varchar,
	CLM_BPRVDR_ADR_ZIP_CD varchar,
	CLM_SUBSCR_CITY_NAME varchar,
	CLM_SUBSCR_USPS_STATE_CD varchar,
	CLM_SUBSCR_ADR_ZIP_CD varchar,
	BENE_CNTY_CD varchar,
	BENE_STATE_CD varchar,
	BENE_MLG_CNTCT_ZIP_CD varchar,
	GNDR_CD varchar,
	BENE_RACE_CD varchar,
	DOB_DT varchar,
	BENE_MDCR_STUS_CD varchar,
	TAX_NUM varchar,
	BENE_STATE varchar,
	RNDRNG_PHYSN_NPI varchar,
	CLM_PLACE_OF_SRVC_CD varchar
)
with(
    appendonly = true,
    orientation = column,
    compresstype = zlib
)
distributed by (BENE_ID);