/* ******************************************************************************************************
 * Changes data source for claims generated by members enrolled in CHIP Perinatal and HTW
 * ******************************************************************************************************
 *  Author || Date      || Notes
 * ******************************************************************************************************
 * xrzhang || 04/04/2023 || Created
 * ------------------------------------------------------------------------------------------------------
 * xrzhang || 09/05/2023 || Moved script order after load - easiest to make changes on live tables
 * 							as they already have the partitions and such
 * ------------------------------------------------------------------------------------------------------
 * xrzhang || 09/13/2023 || Modified script so it backfills in missing uth_member_ids as well
 */
/**********************
 * NOTE: This by necessity makes changes to live tables.
 * The reason for this is because the Medicaid data is all mixed in, so it's easier
 * to deal with it as one big table... but one big table can't be loaded into 3 different partitions,
 * (well it CAN be inserted but it CAN'T be swapped) SO just leave it as one table and then alter the
 * data source afterwards
 **********************/

/*********************
 * Create master list of member_ids and year-months based on monthly enrollment table
 * ******************/
drop table if exists dw_staging.mcpp_mhtw_client_nbr_yrmonth;

create table dw_staging.mcpp_mhtw_client_nbr_yrmonth as
select data_source, uth_member_id, member_id_src, month_year_id,
	to_date((month_year_id*100+01)::text, 'yyyymmdd') as month_start,
	(to_date((month_year_id*100+01)::text, 'yyyymmdd') + interval '1 month - 1 day')::date as month_end
--from dw_staging.mcd_member_enrollment_monthly
from data_warehouse.member_enrollment_monthly
where data_source in ('mcpp', 'mhtw')
distributed by (member_id_src);

analyze dw_staging.mcpp_mhtw_client_nbr_yrmonth;

--select * from dw_staging.mcpp_mhtw_client_nbr_yrmonth;

/*********************
 * Create master list of claims from claim_header originating
 * from members enrolled in CHIP PERI and HTW
 *********************/
drop table if exists dw_staging.mcpp_mhtw_claims;

create table dw_staging.mcpp_mhtw_claims as
select data_source, claim_id_src, uth_member_id, member_id_src
from (
	select a.claim_id_src, a.from_date_of_service, b.*
	from data_warehouse.claim_header_1_prt_mdcd a
	inner join dw_staging.mcpp_mhtw_client_nbr_yrmonth b
	on a.member_id_src = b.member_id_src
		and a.from_date_of_service between b.month_start and b.month_end) t
group by 1, 2, 3, 4
distributed by (claim_id_src);

analyze dw_staging.mcpp_mhtw_claims;

--select * from dw_staging.mcpp_mhtw_claims;

/*********************
 * Relabel claims for each table
 * 
 * Update claim_header last
 * 
 * Note: null uth_member_ids are for people with a claim who are NOT in enrollment tables
 *********************/
--claim_detail
update data_warehouse.claim_detail a
set data_source = b.data_source,
	uth_member_id = b.uth_member_id
from dw_staging.mcpp_mhtw_claims b
where a.data_source = 'mdcd' and
	a.claim_id_src = b.claim_id_src;

vacuum analyze data_warehouse.claim_detail;

--claim_header
update data_warehouse.claim_header a
set data_source = b.data_source,
	uth_member_id = b.uth_member_id
from dw_staging.mcpp_mhtw_claims b
where a.data_source = 'mdcd' and
	a.claim_id_src = b.claim_id_src;

vacuum analyze data_warehouse.claim_header;


