/*
Runs all of the sql scripts in 01-setup

To use, connect to a psql session using 

	psql -h greenplum01.corral.tacc.utexas.edu -d uthealth -U _yourusername_ -W

and enter password when prompted. Then, execute each row individually.

*/

\i H:/GitHub/UTH-CHCD/uthealth-dw/greenplum/datawarehouse/staging-load/truven/01-setup/00-dw-truven-vacuum-analyze-all.sql

\i H:/GitHub/UTH-CHCD/uthealth-dw/greenplum/datawarehouse/staging-load/truven/01-setup/01-dw-truven-dim_uth_member_id.sql

\i H:/GitHub/UTH-CHCD/uthealth-dw/greenplum/datawarehouse/staging-load/truven/01-setup/02-dw-truven-dim_uth_claim_id.sql

\i H:/GitHub/UTH-CHCD/uthealth-dw/greenplum/datawarehouse/staging-load/truven/01-setup/03-dw-truven-dim_uth_rx_id.sql

--------or if you prefer, as a one-liner---------

psql -h greenplum01.corral.tacc.utexas.edu -d uthealth -U xrzhang -W -f "H:\GitHub\UTH-CHCD\uthealth-dw\greenplum\datawarehouse\staging-load\truven\01-setup\02-dw-truven-dim_uth_claim_id.sql"
