/* Create and populate reference look-up table for
 * Truven Service Type
 * Table: ccaes
 * Field: svcscat
 * Ref table: truven.ref_service_type
 * DW table: medical
 * DW field: svc_type
 * Note: Service Type:  (Surgery, Maternity, etc)
*/

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

drop table if exists truven.ref_service_type;

CREATE TABLE truven.ref_service_type (
	"key" int4 NULL,
	value varchar NULL
)
DISTRIBUTED BY ("key");

INSERT INTO truven.ref_service_type ("key", value) VALUES(10110, 'Facility IP Non Acute Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10115, 'Facility IP Non Acute Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10120, 'Facility IP Non Acute ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10130, 'Facility IP Non Acute Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10131, 'Facility IP Non Acute Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10132, 'Facility IP Non Acute DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10134, 'Facility IP Non Acute Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10135, 'Facility IP Non Acute PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10136, 'Facility IP Non Acute Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10137, 'Facility IP Non Acute Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10141, 'Facility IP Non Acute Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10142, 'Facility IP Non Acute Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10151, 'Facility IP Non Acute Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10152, 'Facility IP Non Acute Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10153, 'Facility IP Non Acute Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10154, 'Facility IP Non Acute Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10155, 'Facility IP Non Acute Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10156, 'Facility IP Non Acute Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10159, 'Facility IP Non Acute Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10161, 'Facility IP Non Acute CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10162, 'Facility IP Non Acute Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10163, 'Facility IP Non Acute MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10164, 'Facility IP Non Acute Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10165, 'Facility IP Non Acute PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10166, 'Facility IP Non Acute Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10167, 'Facility IP Non Acute Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10168, 'Facility IP Non Acute X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10169, 'Facility IP Non Acute Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10199, 'Facility IP Non Acute Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10210, 'Facility IP LTC Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10215, 'Facility IP LTC Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10220, 'Facility IP LTC ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10230, 'Facility IP LTC Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10231, 'Facility IP LTC Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10454, 'Facility IP Surgical Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10455, 'Facility IP Surgical Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10456, 'Facility IP Surgical Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10459, 'Facility IP Surgical Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10461, 'Facility IP Surgical CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10462, 'Facility IP Surgical Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10463, 'Facility IP Surgical MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10464, 'Facility IP Surgical Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10465, 'Facility IP Surgical PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10466, 'Facility IP Surgical Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10467, 'Facility IP Surgical Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10468, 'Facility IP Surgical X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10469, 'Facility IP Surgical Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10499, 'Facility IP Surgical Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10510, 'Facility IP Medical Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10515, 'Facility IP Medical Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10520, 'Facility IP Medical ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10530, 'Facility IP Medical Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10531, 'Facility IP Medical Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10532, 'Facility IP Medical DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10534, 'Facility IP Medical Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10535, 'Facility IP Medical PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10536, 'Facility IP Medical Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10537, 'Facility IP Medical Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10541, 'Facility IP Medical Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10542, 'Facility IP Medical Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10551, 'Facility IP Medical Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10552, 'Facility IP Medical Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10553, 'Facility IP Medical Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10554, 'Facility IP Medical Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10555, 'Facility IP Medical Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10556, 'Facility IP Medical Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10559, 'Facility IP Medical Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10561, 'Facility IP Medical CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20299, 'Physician Non-Specialty IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21115, 'Physician Specialty OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21120, 'Physician Specialty OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21124, 'Physician Specialty OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21125, 'Physician Specialty OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21126, 'Physician Specialty OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21188, 'Physician Specialty OP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21199, 'Physician Specialty OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21215, 'Physician Non-Specialty OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21220, 'Physician Non-Specialty OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21224, 'Physician Non-Specialty OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21225, 'Physician Non-Specialty OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21226, 'Physician Non-Specialty OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21288, 'Physician Non-Specialty OP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(21299, 'Physician Non-Specialty OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22115, 'Professional IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22120, 'Professional IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22126, 'Professional IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22130, 'Professional IP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22131, 'Professional IP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22132, 'Professional IP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22135, 'Professional IP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22136, 'Professional IP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22137, 'Professional IP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22140, 'Professional IP Injections');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22141, 'Professional IP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22151, 'Professional IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22152, 'Professional IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22153, 'Professional IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22154, 'Professional IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22155, 'Professional IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22156, 'Professional IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22159, 'Professional IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22161, 'Professional IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30261, 'Mental Health Physician IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30262, 'Mental Health Physician IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30263, 'Mental Health Physician IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30264, 'Mental Health Physician IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30265, 'Mental Health Physician IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30266, 'Mental Health Physician IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30267, 'Mental Health Physician IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30268, 'Mental Health Physician IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30269, 'Mental Health Physician IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30299, 'Mental Health Physician IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30315, 'Mental Health Professional IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30318, 'Mental Health Professional IP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30320, 'Mental Health Professional IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30326, 'Mental Health Professional IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30330, 'Mental Health Professional IP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30331, 'Mental Health Professional IP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30332, 'Mental Health Professional IP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30335, 'Mental Health Professional IP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30336, 'Mental Health Professional IP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30337, 'Mental Health Professional IP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30340, 'Mental Health Professional IP Injections');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30341, 'Mental Health Professional IP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30351, 'Mental Health Professional IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30352, 'Mental Health Professional IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30353, 'Mental Health Professional IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30354, 'Mental Health Professional IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30355, 'Mental Health Professional IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30356, 'Mental Health Professional IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30359, 'Mental Health Professional IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30361, 'Mental Health Professional IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30362, 'Mental Health Professional IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30363, 'Mental Health Professional IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30364, 'Mental Health Professional IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30365, 'Mental Health Professional IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31131, 'Substance Abuse Facility IP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31132, 'Substance Abuse Facility IP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31134, 'Substance Abuse Facility IP Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31135, 'Substance Abuse Facility IP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31136, 'Substance Abuse Facility IP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31137, 'Substance Abuse Facility IP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31141, 'Substance Abuse Facility IP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31142, 'Substance Abuse Facility IP Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31151, 'Substance Abuse Facility IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31152, 'Substance Abuse Facility IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31153, 'Substance Abuse Facility IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31154, 'Substance Abuse Facility IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31155, 'Substance Abuse Facility IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31156, 'Substance Abuse Facility IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31159, 'Substance Abuse Facility IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31161, 'Substance Abuse Facility IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31162, 'Substance Abuse Facility IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31163, 'Substance Abuse Facility IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31164, 'Substance Abuse Facility IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31165, 'Substance Abuse Facility IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31166, 'Substance Abuse Facility IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31167, 'Substance Abuse Facility IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31168, 'Substance Abuse Facility IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31169, 'Substance Abuse Facility IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31199, 'Substance Abuse Facility IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31215, 'Substance Abuse Physician IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31218, 'Substance Abuse Physician IP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31220, 'Substance Abuse Physician IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31226, 'Substance Abuse Physician IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31251, 'Substance Abuse Physician IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31252, 'Substance Abuse Physician IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31253, 'Substance Abuse Physician IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31254, 'Substance Abuse Physician IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31255, 'Substance Abuse Physician IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31624, 'Substance Abuse Professional OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31625, 'Substance Abuse Professional OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31626, 'Substance Abuse Professional OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31630, 'Substance Abuse Professional OP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31631, 'Substance Abuse Professional OP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31632, 'Substance Abuse Professional OP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31633, 'Substance Abuse Professional OP Home Health');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31635, 'Substance Abuse Professional OP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31636, 'Substance Abuse Professional OP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31637, 'Substance Abuse Professional OP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31638, 'Substance Abuse Professional OP Transportation');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31640, 'Substance Abuse Professional OP Injections');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31641, 'Substance Abuse Professional OP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31649, 'Substance Abuse Professional OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31751, 'Substance Abuse OP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31752, 'Substance Abuse OP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31753, 'Substance Abuse OP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31754, 'Substance Abuse OP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31755, 'Substance Abuse OP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31756, 'Substance Abuse OP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31759, 'Substance Abuse OP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31761, 'Substance Abuse OP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10232, 'Facility IP LTC DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10234, 'Facility IP LTC Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10235, 'Facility IP LTC PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10236, 'Facility IP LTC Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10237, 'Facility IP LTC Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10241, 'Facility IP LTC Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10242, 'Facility IP LTC Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10251, 'Facility IP LTC Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10252, 'Facility IP LTC Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10253, 'Facility IP LTC Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10254, 'Facility IP LTC Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10255, 'Facility IP LTC Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10256, 'Facility IP LTC Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10259, 'Facility IP LTC Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10261, 'Facility IP LTC CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10262, 'Facility IP LTC Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10263, 'Facility IP LTC MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10264, 'Facility IP LTC Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10265, 'Facility IP LTC PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10266, 'Facility IP LTC Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10267, 'Facility IP LTC Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10268, 'Facility IP LTC X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10269, 'Facility IP LTC Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10299, 'Facility IP LTC Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10310, 'Facility IP Maternity Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10315, 'Facility IP Maternity Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10320, 'Facility IP Maternity ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10330, 'Facility IP Maternity Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10331, 'Facility IP Maternity Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10332, 'Facility IP Maternity DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10334, 'Facility IP Maternity Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10335, 'Facility IP Maternity PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10336, 'Facility IP Maternity Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10337, 'Facility IP Maternity Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10562, 'Facility IP Medical Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10563, 'Facility IP Medical MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10564, 'Facility IP Medical Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10565, 'Facility IP Medical PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10566, 'Facility IP Medical Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10567, 'Facility IP Medical Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10568, 'Facility IP Medical X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10569, 'Facility IP Medical Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10588, 'Facility IP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10599, 'Facility IP Medical Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12210, 'Facility OP Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12215, 'Facility OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12220, 'Facility OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12328, 'Facility OP Clinic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12330, 'Facility OP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12331, 'Facility OP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12332, 'Facility OP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12333, 'Facility OP Home Health');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12334, 'Facility OP Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12335, 'Facility OP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12336, 'Facility OP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12337, 'Facility OP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12338, 'Facility OP Transportation');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12341, 'Facility OP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12342, 'Facility OP Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12388, 'Facility OP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(12399, 'Facility OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20115, 'Physician Specialty IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20120, 'Physician Specialty IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20126, 'Physician Specialty IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20151, 'Physician Specialty IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20152, 'Physician Specialty IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20153, 'Physician Specialty IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20154, 'Physician Specialty IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22162, 'Professional IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22163, 'Professional IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22164, 'Professional IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22165, 'Professional IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22166, 'Professional IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22167, 'Professional IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22168, 'Professional IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22169, 'Professional IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22199, 'Professional IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22315, 'Professional OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22320, 'Professional OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22324, 'Professional OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22325, 'Professional OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22326, 'Professional OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22327, 'Professional OP Chiropractic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22330, 'Professional OP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22331, 'Professional OP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22332, 'Professional OP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22333, 'Professional OP Home Health');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22335, 'Professional OP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22336, 'Professional OP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22337, 'Professional OP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22338, 'Professional OP Transportation');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22340, 'Professional OP Injections');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22341, 'Professional OP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22399, 'Professional OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(22588, 'Professional Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30110, 'Mental Health Facility IP Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30115, 'Mental Health Facility IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30118, 'Mental Health Facility IP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30120, 'Mental Health Facility IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30130, 'Mental Health Facility IP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30131, 'Mental Health Facility IP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30132, 'Mental Health Facility IP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30366, 'Mental Health Professional IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30367, 'Mental Health Professional IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30368, 'Mental Health Professional IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30369, 'Mental Health Professional IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30399, 'Mental Health Professional IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30410, 'Mental Health Facility OP Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30415, 'Mental Health Facility OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30418, 'Mental Health Facility OP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30420, 'Mental Health Facility OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30428, 'Mental Health Facility OP Clinic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30430, 'Mental Health Facility OP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30431, 'Mental Health Facility OP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30432, 'Mental Health Facility OP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30433, 'Mental Health Facility OP Home Health');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30434, 'Mental Health Facility OP Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30435, 'Mental Health Facility OP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30436, 'Mental Health Facility OP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30437, 'Mental Health Facility OP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30438, 'Mental Health Facility OP Transportation');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30441, 'Mental Health Facility OP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30442, 'Mental Health Facility OP Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30449, 'Mental Health Facility OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30515, 'Mental Health Physician OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30518, 'Mental Health Physician OP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30520, 'Mental Health Physician OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30524, 'Mental Health Physician OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30525, 'Mental Health Physician OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30526, 'Mental Health Physician OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30549, 'Mental Health Physician OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30615, 'Mental Health Professional OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30618, 'Mental Health Professional OP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30620, 'Mental Health Professional OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30624, 'Mental Health Professional OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30625, 'Mental Health Professional OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31256, 'Substance Abuse Physician IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31259, 'Substance Abuse Physician IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31261, 'Substance Abuse Physician IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31262, 'Substance Abuse Physician IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31263, 'Substance Abuse Physician IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31264, 'Substance Abuse Physician IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31265, 'Substance Abuse Physician IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31266, 'Substance Abuse Physician IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31267, 'Substance Abuse Physician IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31268, 'Substance Abuse Physician IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31269, 'Substance Abuse Physician IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31299, 'Substance Abuse Physician IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31315, 'Substance Abuse Professional IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31318, 'Substance Abuse Professional IP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31320, 'Substance Abuse Professional IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31326, 'Substance Abuse Professional IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31330, 'Substance Abuse Professional IP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31331, 'Substance Abuse Professional IP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31332, 'Substance Abuse Professional IP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31335, 'Substance Abuse Professional IP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31336, 'Substance Abuse Professional IP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31337, 'Substance Abuse Professional IP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31340, 'Substance Abuse Professional IP Injections');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31341, 'Substance Abuse Professional IP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31351, 'Substance Abuse Professional IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31352, 'Substance Abuse Professional IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31353, 'Substance Abuse Professional IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31354, 'Substance Abuse Professional IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31355, 'Substance Abuse Professional IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31356, 'Substance Abuse Professional IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31359, 'Substance Abuse Professional IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31361, 'Substance Abuse Professional IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31362, 'Substance Abuse Professional IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31363, 'Substance Abuse Professional IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31763, 'Substance Abuse OP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31763, 'Substance Abuse OP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31764, 'Substance Abuse OP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31765, 'Substance Abuse OP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31766, 'Substance Abuse OP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31767, 'Substance Abuse OP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31768, 'Substance Abuse OP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31769, 'Substance Abuse OP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40151, 'Laboratory OP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40152, 'Laboratory OP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40153, 'Laboratory OP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40154, 'Laboratory OP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40155, 'Laboratory OP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40156, 'Laboratory OP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40159, 'Laboratory OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(40188, 'Laboratory OP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45161, 'Radiology OP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45162, 'Radiology OP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45163, 'Radiology OP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45164, 'Radiology OP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45165, 'Radiology OP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45166, 'Radiology OP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10341, 'Facility IP Maternity Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10342, 'Facility IP Maternity Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10351, 'Facility IP Maternity Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10352, 'Facility IP Maternity Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10353, 'Facility IP Maternity Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10354, 'Facility IP Maternity Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10355, 'Facility IP Maternity Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10356, 'Facility IP Maternity Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10359, 'Facility IP Maternity Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10361, 'Facility IP Maternity CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10362, 'Facility IP Maternity Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10363, 'Facility IP Maternity MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10364, 'Facility IP Maternity Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10365, 'Facility IP Maternity PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10366, 'Facility IP Maternity Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10367, 'Facility IP Maternity Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10368, 'Facility IP Maternity X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10369, 'Facility IP Maternity Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10399, 'Facility IP Maternity Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10410, 'Facility IP Surgical Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10415, 'Facility IP Surgical Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10420, 'Facility IP Surgical ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10430, 'Facility IP Surgical Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10431, 'Facility IP Surgical Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10432, 'Facility IP Surgical DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10434, 'Facility IP Surgical Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10435, 'Facility IP Surgical PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10436, 'Facility IP Surgical Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10437, 'Facility IP Surgical Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10441, 'Facility IP Surgical Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10442, 'Facility IP Surgical Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10451, 'Facility IP Surgical Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10452, 'Facility IP Surgical Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(10453, 'Facility IP Surgical Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20155, 'Physician Specialty IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20156, 'Physician Specialty IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20159, 'Physician Specialty IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20161, 'Physician Specialty IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20162, 'Physician Specialty IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20163, 'Physician Specialty IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20164, 'Physician Specialty IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20165, 'Physician Specialty IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20166, 'Physician Specialty IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20167, 'Physician Specialty IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20168, 'Physician Specialty IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20169, 'Physician Specialty IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20188, 'Physician Specialty IP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20199, 'Physician Specialty IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20215, 'Physician Non-Specialty IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20220, 'Physician Non-Specialty IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20226, 'Physician Non-Specialty IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20251, 'Physician Non-Specialty IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20252, 'Physician Non-Specialty IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20253, 'Physician Non-Specialty IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20254, 'Physician Non-Specialty IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20255, 'Physician Non-Specialty IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20256, 'Physician Non-Specialty IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20259, 'Physician Non-Specialty IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20261, 'Physician Non-Specialty IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20262, 'Physician Non-Specialty IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20263, 'Physician Non-Specialty IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20264, 'Physician Non-Specialty IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20265, 'Physician Non-Specialty IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20266, 'Physician Non-Specialty IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20267, 'Physician Non-Specialty IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20268, 'Physician Non-Specialty IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20269, 'Physician Non-Specialty IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(20288, 'Physician Non-Specialty IP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30134, 'Mental Health Facility IP Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30135, 'Mental Health Facility IP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30136, 'Mental Health Facility IP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30137, 'Mental Health Facility IP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30141, 'Mental Health Facility IP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30142, 'Mental Health Facility IP Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30151, 'Mental Health Facility IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30152, 'Mental Health Facility IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30153, 'Mental Health Facility IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30154, 'Mental Health Facility IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30155, 'Mental Health Facility IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30156, 'Mental Health Facility IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30159, 'Mental Health Facility IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30161, 'Mental Health Facility IP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30162, 'Mental Health Facility IP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30163, 'Mental Health Facility IP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30164, 'Mental Health Facility IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30165, 'Mental Health Facility IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30166, 'Mental Health Facility IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30167, 'Mental Health Facility IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30168, 'Mental Health Facility IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30169, 'Mental Health Facility IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30199, 'Mental Health Facility IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30215, 'Mental Health Physician IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30218, 'Mental Health Physician IP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30220, 'Mental Health Physician IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30226, 'Mental Health Physician IP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30251, 'Mental Health Physician IP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30252, 'Mental Health Physician IP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30253, 'Mental Health Physician IP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30254, 'Mental Health Physician IP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30255, 'Mental Health Physician IP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30256, 'Mental Health Physician IP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30259, 'Mental Health Physician IP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30626, 'Mental Health Professional OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30630, 'Mental Health Professional OP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30631, 'Mental Health Professional OP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30632, 'Mental Health Professional OP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30633, 'Mental Health Professional OP Home Health');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30635, 'Mental Health Professional OP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30636, 'Mental Health Professional OP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30637, 'Mental Health Professional OP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30638, 'Mental Health Professional OP Transportation');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30640, 'Mental Health Professional OP Injections');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30641, 'Mental Health Professional OP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30649, 'Mental Health Professional OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30751, 'Mental Health OP Chemistry Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30752, 'Mental Health OP Hematology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30753, 'Mental Health OP Immunology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30754, 'Mental Health OP Microbiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30755, 'Mental Health OP Pathology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30756, 'Mental Health OP Urinalysis Tests');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30759, 'Mental Health OP Laboratory Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30761, 'Mental Health OP CAT Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30762, 'Mental Health OP Mammograms');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30763, 'Mental Health OP MRIs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30764, 'Mental Health OP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30765, 'Mental Health OP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30766, 'Mental Health OP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30767, 'Mental Health OP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30768, 'Mental Health OP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30769, 'Mental Health OP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(30888, 'MHSA Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31110, 'Substance Abuse Facility IP Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31115, 'Substance Abuse Facility IP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31118, 'Substance Abuse Facility IP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31120, 'Substance Abuse Facility IP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31130, 'Substance Abuse Facility IP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31364, 'Substance Abuse Professional IP Nuclear Medicine');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31365, 'Substance Abuse Professional IP PET Scans');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31366, 'Substance Abuse Professional IP Therapeutic Radiology');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31367, 'Substance Abuse Professional IP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31368, 'Substance Abuse Professional IP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31369, 'Substance Abuse Professional IP Radiology Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31399, 'Substance Abuse Professional IP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31410, 'Substance Abuse Facility OP Room and Board');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31415, 'Substance Abuse Facility OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31418, 'Substance Abuse Facility OP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31420, 'Substance Abuse Facility OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31428, 'Substance Abuse Facility OP Clinic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31430, 'Substance Abuse Facility OP Diagnostic Services');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31431, 'Substance Abuse Facility OP Dialysis');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31432, 'Substance Abuse Facility OP DME');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31433, 'Substance Abuse Facility OP Home Health');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31434, 'Substance Abuse Facility OP Pharmacy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31435, 'Substance Abuse Facility OP PT, OT, Speech Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31436, 'Substance Abuse Facility OP Specialty Drugs');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31437, 'Substance Abuse Facility OP Supplies and Devices');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31438, 'Substance Abuse Facility OP Transportation');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31441, 'Substance Abuse Facility OP Respiratory Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31442, 'Substance Abuse Facility OP Hospice Care');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31449, 'Substance Abuse Facility OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31515, 'Substance Abuse Physician OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31518, 'Substance Abuse Physician OP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31520, 'Substance Abuse Physician OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31524, 'Substance Abuse Physician OP Preventive Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31525, 'Substance Abuse Physician OP Office Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31526, 'Substance Abuse Physician OP Facility Visits');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31549, 'Substance Abuse Physician OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31615, 'Substance Abuse Professional OP Procedures');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31618, 'Substance Abuse Professional OP Behavioral Health Therapy');
INSERT INTO truven.ref_service_type ("key", value) VALUES(31620, 'Substance Abuse Professional OP ER');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45167, 'Radiology OP Ultrasounds');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45168, 'Radiology OP X-Rays');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45169, 'Radiology OP Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(45188, 'Radiology OP Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(50170, 'Specialty Drugs Mail Order');
INSERT INTO truven.ref_service_type ("key", value) VALUES(50171, 'Specialty Drugs Retail');
INSERT INTO truven.ref_service_type ("key", value) VALUES(50172, 'Non-Specialty Drugs Mail Order');
INSERT INTO truven.ref_service_type ("key", value) VALUES(50175, 'Non-Specialty Drugs Retail');
INSERT INTO truven.ref_service_type ("key", value) VALUES(50188, 'Prescription Drugs Non-Claim Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(70180, 'Administrative Fees');
INSERT INTO truven.ref_service_type ("key", value) VALUES(70181, 'Capitation Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(70182, 'Premium Payments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(70183, 'Employee Premium Contributions');
INSERT INTO truven.ref_service_type ("key", value) VALUES(70187, 'Bulk Adjustments');
INSERT INTO truven.ref_service_type ("key", value) VALUES(70199, 'Non-Claim Payments Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80190, 'Dental Diagnostic and Preventive');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80191, 'Dental Basic Restorative');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80192, 'Dental Major Restorative');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80193, 'Dental Orthodontics');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80194, 'Dental Other');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80196, 'Vision');
INSERT INTO truven.ref_service_type ("key", value) VALUES(80199, 'Hearing and Other Benefits');

commit;

-- Test join
select distinct lu.value, t.svcscat
from truven.ccaes as t 
join truven.ref_service_type lu on (t.svcscat = lu."key")
limit 100;