drop external table ext_bcarrier_line_k;

CREATE EXTERNAL TABLE ext_bcarrier_line_k (
year text, filename text,
BENE_ID varchar, CLM_ID varchar, LINE_NUM varchar, NCH_CLM_TYPE_CD varchar, CLM_THRU_DT varchar, CARR_PRFRNG_PIN_NUM varchar, 
PRF_PHYSN_UPIN varchar, PRF_PHYSN_NPI varchar, ORG_NPI_NUM varchar, CARR_LINE_PRVDR_TYPE_CD varchar, TAX_NUM varchar, PRVDR_STATE_CD varchar, 
PRVDR_ZIP varchar, PRVDR_SPCLTY varchar, PRTCPTNG_IND_CD varchar, CARR_LINE_RDCD_PMT_PHYS_ASTN_C varchar, LINE_SRVC_CNT varchar, 
LINE_CMS_TYPE_SRVC_CD varchar, LINE_PLACE_OF_SRVC_CD varchar, CARR_LINE_PRCNG_LCLTY_CD varchar, LINE_1ST_EXPNS_DT varchar, 
LINE_LAST_EXPNS_DT varchar, HCPCS_CD varchar, HCPCS_1ST_MDFR_CD varchar, HCPCS_2ND_MDFR_CD varchar, BETOS_CD varchar, 
LINE_NCH_PMT_AMT varchar, LINE_BENE_PMT_AMT varchar, LINE_PRVDR_PMT_AMT varchar, LINE_BENE_PTB_DDCTBL_AMT varchar, 
LINE_BENE_PRMRY_PYR_CD varchar, LINE_BENE_PRMRY_PYR_PD_AMT varchar, LINE_COINSRNC_AMT varchar, LINE_SBMTD_CHRG_AMT varchar, 
LINE_ALOWD_CHRG_AMT varchar, LINE_PRCSG_IND_CD varchar, LINE_PMT_80_100_CD varchar, LINE_SERVICE_DEDUCTIBLE varchar, 
CARR_LINE_MTUS_CNT varchar, CARR_LINE_MTUS_CD varchar, LINE_ICD_DGNS_CD varchar, LINE_ICD_DGNS_VRSN_CD varchar, HPSA_SCRCTY_IND_CD varchar, 
CARR_LINE_RX_NUM varchar, LINE_HCT_HGB_RSLT_NUM varchar, LINE_HCT_HGB_TYPE_CD varchar, LINE_NDC_CD varchar, CARR_LINE_CLIA_LAB_NUM varchar, 
CARR_LINE_ANSTHSA_UNIT_CNT varchar, CARR_LINE_CL_CHRG_AMT varchar, PHYSN_dod_CD varchar, LINE_OTHR_APLD_IND_CD1 varchar, 
LINE_OTHR_APLD_IND_CD2 varchar, LINE_OTHR_APLD_IND_CD3 varchar, LINE_OTHR_APLD_IND_CD4 varchar, LINE_OTHR_APLD_IND_CD5 varchar, 
LINE_OTHR_APLD_IND_CD6 varchar, LINE_OTHR_APLD_IND_CD7 varchar, LINE_OTHR_APLD_AMT1 varchar, LINE_OTHR_APLD_AMT2 varchar, 
LINE_OTHR_APLD_AMT3 varchar, LINE_OTHR_APLD_AMT4 varchar, LINE_OTHR_APLD_AMT5 varchar, LINE_OTHR_APLD_AMT6 varchar, 
LINE_OTHR_APLD_AMT7 varchar, THRPY_CAP_IND_CD1 varchar, THRPY_CAP_IND_CD2 varchar, THRPY_CAP_IND_CD3 varchar, THRPY_CAP_IND_CD4 varchar, 
THRPY_CAP_IND_CD5 varchar, CLM_NEXT_GNRTN_ACO_IND_CD1 varchar, CLM_NEXT_GNRTN_ACO_IND_CD2 varchar, CLM_NEXT_GNRTN_ACO_IND_CD3 varchar, 
CLM_NEXT_GNRTN_ACO_IND_CD4 varchar, CLM_NEXT_GNRTN_ACO_IND_CD5 varchar,CARR_LINE_MDPP_NPI_NUM varchar,
LINE_RSDL_PYMT_IND_CD varchar, LINE_RP_IND_CD varchar, LINE_PRVDR_VLDTN_TYPE_CD varchar
) 
LOCATION ( 
'gpfdist://192.168.58.179:8081/medicare_national/201*/*bcarrier_line_k.csv.gz#transform=add_parentname_filename_comma'
)
FORMAT 'CSV' ( HEADER DELIMITER ',' );

select *
from ext_bcarrier_line_k
limit 1000;

create table medicare_national.bcarrier_line_k
WITH (appendonly=true, orientation=column, compresstype=zlib)
as
insert into medicare_national.bcarrier_line_k (year,
BENE_ID, CLM_ID, LINE_NUM, NCH_CLM_TYPE_CD, CLM_THRU_DT, CARR_PRFRNG_PIN_NUM, 
PRF_PHYSN_UPIN, PRF_PHYSN_NPI, ORG_NPI_NUM, CARR_LINE_PRVDR_TYPE_CD, TAX_NUM, PRVDR_STATE_CD, 
PRVDR_ZIP, PRVDR_SPCLTY, PRTCPTNG_IND_CD, CARR_LINE_RDCD_PMT_PHYS_ASTN_C, LINE_SRVC_CNT, 
LINE_CMS_TYPE_SRVC_CD, LINE_PLACE_OF_SRVC_CD, CARR_LINE_PRCNG_LCLTY_CD, LINE_1ST_EXPNS_DT, 
LINE_LAST_EXPNS_DT, HCPCS_CD, HCPCS_1ST_MDFR_CD, HCPCS_2ND_MDFR_CD, BETOS_CD, 
LINE_NCH_PMT_AMT, LINE_BENE_PMT_AMT, LINE_PRVDR_PMT_AMT, LINE_BENE_PTB_DDCTBL_AMT, 
LINE_BENE_PRMRY_PYR_CD, LINE_BENE_PRMRY_PYR_PD_AMT, LINE_COINSRNC_AMT, LINE_SBMTD_CHRG_AMT, 
LINE_ALOWD_CHRG_AMT, LINE_PRCSG_IND_CD, LINE_PMT_80_100_CD, LINE_SERVICE_DEDUCTIBLE, 
CARR_LINE_MTUS_CNT, CARR_LINE_MTUS_CD, LINE_ICD_DGNS_CD, LINE_ICD_DGNS_VRSN_CD, HPSA_SCRCTY_IND_CD, 
CARR_LINE_RX_NUM, LINE_HCT_HGB_RSLT_NUM, LINE_HCT_HGB_TYPE_CD, LINE_NDC_CD, CARR_LINE_CLIA_LAB_NUM, 
CARR_LINE_ANSTHSA_UNIT_CNT, CARR_LINE_CL_CHRG_AMT, PHYSN_dod_CD, LINE_OTHR_APLD_IND_CD1, 
LINE_OTHR_APLD_IND_CD2, LINE_OTHR_APLD_IND_CD3, LINE_OTHR_APLD_IND_CD4, LINE_OTHR_APLD_IND_CD5, 
LINE_OTHR_APLD_IND_CD6, LINE_OTHR_APLD_IND_CD7, LINE_OTHR_APLD_AMT1, LINE_OTHR_APLD_AMT2, 
LINE_OTHR_APLD_AMT3, LINE_OTHR_APLD_AMT4, LINE_OTHR_APLD_AMT5, LINE_OTHR_APLD_AMT6, 
LINE_OTHR_APLD_AMT7, THRPY_CAP_IND_CD1, THRPY_CAP_IND_CD2, THRPY_CAP_IND_CD3, THRPY_CAP_IND_CD4, 
THRPY_CAP_IND_CD5, CLM_NEXT_GNRTN_ACO_IND_CD1, CLM_NEXT_GNRTN_ACO_IND_CD2, CLM_NEXT_GNRTN_ACO_IND_CD3, 
CLM_NEXT_GNRTN_ACO_IND_CD4, CLM_NEXT_GNRTN_ACO_IND_CD5,CARR_LINE_MDPP_NPI_NUM,
LINE_RSDL_PYMT_IND_CD,LINE_RP_IND_CD,LINE_PRVDR_VLDTN_TYPE_CD
)
select year,
BENE_ID, CLM_ID, LINE_NUM, NCH_CLM_TYPE_CD, CLM_THRU_DT, CARR_PRFRNG_PIN_NUM, 
PRF_PHYSN_UPIN, PRF_PHYSN_NPI, ORG_NPI_NUM, CARR_LINE_PRVDR_TYPE_CD, TAX_NUM, PRVDR_STATE_CD, 
PRVDR_ZIP, PRVDR_SPCLTY, PRTCPTNG_IND_CD, CARR_LINE_RDCD_PMT_PHYS_ASTN_C, LINE_SRVC_CNT, 
LINE_CMS_TYPE_SRVC_CD, LINE_PLACE_OF_SRVC_CD, CARR_LINE_PRCNG_LCLTY_CD, LINE_1ST_EXPNS_DT, 
LINE_LAST_EXPNS_DT, HCPCS_CD, HCPCS_1ST_MDFR_CD, HCPCS_2ND_MDFR_CD, BETOS_CD, 
LINE_NCH_PMT_AMT, LINE_BENE_PMT_AMT, LINE_PRVDR_PMT_AMT, LINE_BENE_PTB_DDCTBL_AMT, 
LINE_BENE_PRMRY_PYR_CD, LINE_BENE_PRMRY_PYR_PD_AMT, LINE_COINSRNC_AMT, LINE_SBMTD_CHRG_AMT, 
LINE_ALOWD_CHRG_AMT, LINE_PRCSG_IND_CD, LINE_PMT_80_100_CD, LINE_SERVICE_DEDUCTIBLE, 
CARR_LINE_MTUS_CNT, CARR_LINE_MTUS_CD, LINE_ICD_DGNS_CD, LINE_ICD_DGNS_VRSN_CD, HPSA_SCRCTY_IND_CD, 
CARR_LINE_RX_NUM, LINE_HCT_HGB_RSLT_NUM, LINE_HCT_HGB_TYPE_CD, LINE_NDC_CD, CARR_LINE_CLIA_LAB_NUM, 
CARR_LINE_ANSTHSA_UNIT_CNT, CARR_LINE_CL_CHRG_AMT, PHYSN_dod_CD, LINE_OTHR_APLD_IND_CD1, 
LINE_OTHR_APLD_IND_CD2, LINE_OTHR_APLD_IND_CD3, LINE_OTHR_APLD_IND_CD4, LINE_OTHR_APLD_IND_CD5, 
LINE_OTHR_APLD_IND_CD6, LINE_OTHR_APLD_IND_CD7, LINE_OTHR_APLD_AMT1, LINE_OTHR_APLD_AMT2, 
LINE_OTHR_APLD_AMT3, LINE_OTHR_APLD_AMT4, LINE_OTHR_APLD_AMT5, LINE_OTHR_APLD_AMT6, 
LINE_OTHR_APLD_AMT7, THRPY_CAP_IND_CD1, THRPY_CAP_IND_CD2, THRPY_CAP_IND_CD3, THRPY_CAP_IND_CD4, 
THRPY_CAP_IND_CD5, CLM_NEXT_GNRTN_ACO_IND_CD1, CLM_NEXT_GNRTN_ACO_IND_CD2, CLM_NEXT_GNRTN_ACO_IND_CD3, 
CLM_NEXT_GNRTN_ACO_IND_CD4, CLM_NEXT_GNRTN_ACO_IND_CD5,CARR_LINE_MDPP_NPI_NUM,
LINE_RSDL_PYMT_IND_CD,LINE_RP_IND_CD,LINE_PRVDR_VLDTN_TYPE_CD
from ext_bcarrier_line_k;


-- 2018: added LINE_RSDL_PYMT_IND_CD,LINE_RP_IND_CD,LINE_PRVDR_VLDTN_TYPE_CD
/*
BENE_ID,CLM_ID,LINE_NUM,NCH_CLM_TYPE_CD,CLM_THRU_DT,CARR_PRFRNG_PIN_NUM,
PRF_PHYSN_UPIN,PRF_PHYSN_NPI,ORG_NPI_NUM,CARR_LINE_PRVDR_TYPE_CD,TAX_NUM,PRVDR_STATE_CD,
PRVDR_ZIP,PRVDR_SPCLTY,PRTCPTNG_IND_CD,CARR_LINE_RDCD_PMT_PHYS_ASTN_C,LINE_SRVC_CNT,
LINE_CMS_TYPE_SRVC_CD,LINE_PLACE_OF_SRVC_CD,CARR_LINE_PRCNG_LCLTY_CD,LINE_1ST_EXPNS_DT,
LINE_LAST_EXPNS_DT,HCPCS_CD,HCPCS_1ST_MDFR_CD,HCPCS_2ND_MDFR_CD,BETOS_CD,
LINE_NCH_PMT_AMT,LINE_BENE_PMT_AMT,LINE_PRVDR_PMT_AMT,LINE_BENE_PTB_DDCTBL_AMT,
LINE_BENE_PRMRY_PYR_CD,LINE_BENE_PRMRY_PYR_PD_AMT,LINE_COINSRNC_AMT,LINE_SBMTD_CHRG_AMT,
LINE_ALOWD_CHRG_AMT,LINE_PRCSG_IND_CD,LINE_PMT_80_100_CD,LINE_SERVICE_DEDUCTIBLE,
CARR_LINE_MTUS_CNT,CARR_LINE_MTUS_CD,LINE_ICD_DGNS_CD,LINE_ICD_DGNS_VRSN_CD,HPSA_SCRCTY_IND_CD,
CARR_LINE_RX_NUM,LINE_HCT_HGB_RSLT_NUM,LINE_HCT_HGB_TYPE_CD,LINE_NDC_CD,CARR_LINE_CLIA_LAB_NUM,
CARR_LINE_ANSTHSA_UNIT_CNT,CARR_LINE_CL_CHRG_AMT,PHYSN_dod_CD,LINE_OTHR_APLD_IND_CD1,
LINE_OTHR_APLD_IND_CD2,LINE_OTHR_APLD_IND_CD3,LINE_OTHR_APLD_IND_CD4,LINE_OTHR_APLD_IND_CD5,
LINE_OTHR_APLD_IND_CD6,LINE_OTHR_APLD_IND_CD7,LINE_OTHR_APLD_AMT1,LINE_OTHR_APLD_AMT2,
LINE_OTHR_APLD_AMT3,LINE_OTHR_APLD_AMT4,LINE_OTHR_APLD_AMT5,LINE_OTHR_APLD_AMT6,
LINE_OTHR_APLD_AMT7,THRPY_CAP_IND_CD1,THRPY_CAP_IND_CD2,THRPY_CAP_IND_CD3,THRPY_CAP_IND_CD4,
THRPY_CAP_IND_CD5,CLM_NEXT_GNRTN_ACO_IND_CD1,CLM_NEXT_GNRTN_ACO_IND_CD2,CLM_NEXT_GNRTN_ACO_IND_CD3,
CLM_NEXT_GNRTN_ACO_IND_CD4,CLM_NEXT_GNRTN_ACO_IND_CD5,CARR_LINE_MDPP_NPI_NUM,
LINE_RSDL_PYMT_IND_CD,LINE_RP_IND_CD,LINE_PRVDR_VLDTN_TYPE_CD
 */
alter table medicare_national.bcarrier_line_k add column LINE_RSDL_PYMT_IND_CD varchar;
alter table medicare_national.bcarrier_line_k add column LINE_RP_IND_CD varchar;
alter table medicare_national.bcarrier_line_k add column LINE_PRVDR_VLDTN_TYPE_CD varchar;

-- Scratch

select year, min(clm_thru_dt), max(clm_thru_dt), count(*)
from medicare_national.bcarrier_line_k pf 
group by 1
order by 1;