drop external table ext_mbsf_abcd_summary;

CREATE EXTERNAL TABLE ext_mbsf_abcd_summary (
year text, filename text,
BENE_ID varchar,BENE_ENROLLMT_REF_YR varchar,ENRL_SRC varchar,SAMPLE_GROUP varchar,ENHANCED_FIVE_PERCENT_FLAG varchar,CRNT_BIC_CD varchar,STATE_CODE varchar,COUNTY_CD varchar,ZIP_CD varchar,
STATE_CNTY_FIPS_CD_01 varchar,STATE_CNTY_FIPS_CD_02 varchar,STATE_CNTY_FIPS_CD_03 varchar,STATE_CNTY_FIPS_CD_04 varchar,STATE_CNTY_FIPS_CD_05 varchar,STATE_CNTY_FIPS_CD_06 varchar,STATE_CNTY_FIPS_CD_07 varchar,STATE_CNTY_FIPS_CD_08 varchar,
STATE_CNTY_FIPS_CD_09 varchar,STATE_CNTY_FIPS_CD_10 varchar,STATE_CNTY_FIPS_CD_11 varchar,STATE_CNTY_FIPS_CD_12 varchar,
AGE_AT_END_REF_YR varchar,BENE_BIRTH_DT varchar,VALID_DEATH_DT_SW varchar,BENE_DEATH_DT varchar,SEX_IDENT_CD varchar,BENE_RACE_CD varchar,RTI_RACE_CD varchar,COVSTART varchar,ENTLMT_RSN_ORIG varchar,ENTLMT_RSN_CURR varchar,ESRD_IND varchar,
MDCR_STATUS_CODE_01 varchar,MDCR_STATUS_CODE_02 varchar,MDCR_STATUS_CODE_03 varchar,MDCR_STATUS_CODE_04 varchar,MDCR_STATUS_CODE_05 varchar,MDCR_STATUS_CODE_06 varchar,
MDCR_STATUS_CODE_07 varchar,MDCR_STATUS_CODE_08 varchar,MDCR_STATUS_CODE_09 varchar,MDCR_STATUS_CODE_10 varchar,MDCR_STATUS_CODE_11 varchar,MDCR_STATUS_CODE_12 varchar,
BENE_PTA_TRMNTN_CD varchar,BENE_PTB_TRMNTN_CD varchar,BENE_HI_CVRAGE_TOT_MONS varchar,BENE_SMI_CVRAGE_TOT_MONS varchar,BENE_STATE_BUYIN_TOT_MONS varchar,BENE_HMO_CVRAGE_TOT_MONS varchar,PTD_PLAN_CVRG_MONS varchar,
RDS_CVRG_MONS varchar,DUAL_ELGBL_MONS varchar,
MDCR_ENTLMT_BUYIN_IND_01 varchar,MDCR_ENTLMT_BUYIN_IND_02 varchar,MDCR_ENTLMT_BUYIN_IND_03 varchar,MDCR_ENTLMT_BUYIN_IND_04 varchar,MDCR_ENTLMT_BUYIN_IND_05 varchar,MDCR_ENTLMT_BUYIN_IND_06 varchar,
MDCR_ENTLMT_BUYIN_IND_07 varchar,MDCR_ENTLMT_BUYIN_IND_08 varchar,MDCR_ENTLMT_BUYIN_IND_09 varchar,MDCR_ENTLMT_BUYIN_IND_10 varchar,MDCR_ENTLMT_BUYIN_IND_11 varchar,MDCR_ENTLMT_BUYIN_IND_12 varchar,
HMO_IND_01 varchar,HMO_IND_02 varchar,HMO_IND_03 varchar,HMO_IND_04 varchar,HMO_IND_05 varchar,HMO_IND_06 varchar,
HMO_IND_07 varchar,HMO_IND_08 varchar,HMO_IND_09 varchar,HMO_IND_10 varchar,HMO_IND_11 varchar,HMO_IND_12 varchar,
PTC_CNTRCT_ID_01 varchar,PTC_CNTRCT_ID_02 varchar,PTC_CNTRCT_ID_03 varchar,PTC_CNTRCT_ID_04 varchar,PTC_CNTRCT_ID_05 varchar,PTC_CNTRCT_ID_06 varchar,
PTC_CNTRCT_ID_07 varchar,PTC_CNTRCT_ID_08 varchar,PTC_CNTRCT_ID_09 varchar,PTC_CNTRCT_ID_10 varchar,PTC_CNTRCT_ID_11 varchar,PTC_CNTRCT_ID_12 varchar,
PTC_PBP_ID_01 varchar,PTC_PBP_ID_02 varchar,PTC_PBP_ID_03 varchar,PTC_PBP_ID_04 varchar,PTC_PBP_ID_05 varchar,PTC_PBP_ID_06 varchar,
PTC_PBP_ID_07 varchar,PTC_PBP_ID_08 varchar,PTC_PBP_ID_09 varchar,PTC_PBP_ID_10 varchar,PTC_PBP_ID_11 varchar,PTC_PBP_ID_12 varchar,
PTC_PLAN_TYPE_CD_01 varchar,PTC_PLAN_TYPE_CD_02 varchar,PTC_PLAN_TYPE_CD_03 varchar,PTC_PLAN_TYPE_CD_04 varchar,PTC_PLAN_TYPE_CD_05 varchar,PTC_PLAN_TYPE_CD_06 varchar,
PTC_PLAN_TYPE_CD_07 varchar,PTC_PLAN_TYPE_CD_08 varchar,PTC_PLAN_TYPE_CD_09 varchar,PTC_PLAN_TYPE_CD_10 varchar,PTC_PLAN_TYPE_CD_11 varchar,PTC_PLAN_TYPE_CD_12 varchar,
PTD_CNTRCT_ID_01 varchar,PTD_CNTRCT_ID_02 varchar,PTD_CNTRCT_ID_03 varchar,PTD_CNTRCT_ID_04 varchar,PTD_CNTRCT_ID_05 varchar,PTD_CNTRCT_ID_06 varchar,
PTD_CNTRCT_ID_07 varchar,PTD_CNTRCT_ID_08 varchar,PTD_CNTRCT_ID_09 varchar,PTD_CNTRCT_ID_10 varchar,PTD_CNTRCT_ID_11 varchar,PTD_CNTRCT_ID_12 varchar,
PTD_PBP_ID_01 varchar,PTD_PBP_ID_02 varchar,PTD_PBP_ID_03 varchar,PTD_PBP_ID_04 varchar,PTD_PBP_ID_05 varchar,PTD_PBP_ID_06 varchar,
PTD_PBP_ID_07 varchar,PTD_PBP_ID_08 varchar,PTD_PBP_ID_09 varchar,PTD_PBP_ID_10 varchar,PTD_PBP_ID_11 varchar,PTD_PBP_ID_12 varchar,
PTD_SGMT_ID_01 varchar,PTD_SGMT_ID_02 varchar,PTD_SGMT_ID_03 varchar,PTD_SGMT_ID_04 varchar,PTD_SGMT_ID_05 varchar,PTD_SGMT_ID_06
 varchar,PTD_SGMT_ID_07 varchar,PTD_SGMT_ID_08 varchar,PTD_SGMT_ID_09 varchar,PTD_SGMT_ID_10 varchar,PTD_SGMT_ID_11 varchar,PTD_SGMT_ID_12 varchar,
RDS_IND_01 varchar,RDS_IND_02 varchar,RDS_IND_03 varchar,RDS_IND_04 varchar,RDS_IND_05 varchar,RDS_IND_06 varchar,
RDS_IND_07 varchar,RDS_IND_08 varchar,RDS_IND_09 varchar,RDS_IND_10 varchar,RDS_IND_11 varchar,RDS_IND_12 varchar,
DUAL_STUS_CD_01 varchar,DUAL_STUS_CD_02 varchar,DUAL_STUS_CD_03 varchar,DUAL_STUS_CD_04 varchar,DUAL_STUS_CD_05 varchar,DUAL_STUS_CD_06 varchar,
DUAL_STUS_CD_07 varchar,DUAL_STUS_CD_08 varchar,DUAL_STUS_CD_09 varchar,DUAL_STUS_CD_10 varchar,DUAL_STUS_CD_11 varchar,DUAL_STUS_CD_12 varchar,
CST_SHR_GRP_CD_01 varchar,CST_SHR_GRP_CD_02 varchar,CST_SHR_GRP_CD_03 varchar,CST_SHR_GRP_CD_04 varchar,CST_SHR_GRP_CD_05 varchar,CST_SHR_GRP_CD_06 varchar,
CST_SHR_GRP_CD_07 varchar,CST_SHR_GRP_CD_08 varchar,CST_SHR_GRP_CD_09 varchar,CST_SHR_GRP_CD_10 varchar,CST_SHR_GRP_CD_11 varchar,CST_SHR_GRP_CD_12 varchar
) 
LOCATION ( 
'gpfdist://192.168.58.179:8081/medicare_national/*/*mbsf_abcd_summary.csv.gz#transform=add_parentname_filename_comma'
)
FORMAT 'CSV' ( HEADER DELIMITER ',' );

select *
from ext_mbsf_abcd_summary
limit 1000;

create table medicare_national.mbsf_abcd_summary
WITH (appendonly=true, orientation=column, compresstype=zlib)
as

--insert into medicare_national.mbsf_abcd_summary
select * --NOTE: Add column order
from ext_mbsf_abcd_summary
distributed randomly;

-- Scratch
select year, count(*)
from medicare_national.mbsf_abcd_summary
group by 1
order by 1;