drop table if exists medicare_texas.mbsf_chronic_summary;

create table medicare_texas.mbsf_chronic_summary
(
    year text,
    BENE_ID varchar,
	BENE_ENROLLMT_REF_YR varchar,
	ALZH varchar,
	ALZH_EVER varchar,
	AMI varchar,
	AMI_EVER varchar,
	ANEMIA varchar,
	ANEMIA_EVER varchar,
	ASTHMA varchar,
	ASTHMA_EVER varchar,
	ATRIAL_FIB varchar,
	ATRIAL_FIB_EVER varchar,
	BPH varchar,
	BPH_EVER varchar,
	CANCER_BREAST varchar,
	CANCER_BREAST_EVER varchar,
	CANCER_COLORECTAL varchar,
	CANCER_COLORECTAL_EVER varchar,
	CANCER_ENDOMETRIAL varchar,
	CANCER_ENDOMETRIAL_EVER varchar,
	CANCER_LUNG varchar,
	CANCER_LUNG_EVER varchar,
	CANCER_PROSTATE varchar,
	CANCER_PROSTATE_EVER varchar,
	CANCER_UROLOGIC varchar,
	CANCER_UROLOGIC_EVER varchar,
	CATARACT varchar,
	CATARACT_EVER varchar,
	CHRONICKIDNEY varchar,
	CHRONICKIDNEY_EVER varchar,
	COPD varchar,
	COPD_EVER varchar,
	DEPRESSION varchar,
	DEPRESSION_EVER varchar,
	DIABETES varchar,
	DIABETES_EVER varchar,
	GLAUCOMA varchar,
	GLAUCOMA_EVER varchar,
	HF varchar,
	HF_EVER varchar,
	HIP_FRACTURE varchar,
	HIP_FRACTURE_EVER varchar,
	HLP varchar,
	HLP_EVER varchar,
	HTN varchar,
	HTN_EVER varchar,
	HYPTHYRD varchar,
	HYPTHYRD_EVER varchar,
	ISCHEMICHEART varchar,
	ISCHEMICHEART_EVER varchar,
	NONALZH_DEMEN varchar,
	NONALZH_DEMEN_EVER varchar,
	OSTEOPOROSIS varchar,
	OSTEOPOROSIS_EVER varchar,
	PNEUMO varchar,
	PNEUMO_EVER varchar,
	PRKNSN varchar,
	PRKNSN_EVER varchar,
	RA_OA varchar,
	RA_OA_EVER varchar,
	STROKE_TIA varchar,
	STROKE_TIA_EVER varchar
	)
with(
	appendonly = true,
	orientation = column,
	compresstype = zlib
)
distributed by (BENE_ID);

