---
title: "Upload 5 Agency Wellness codes to Greenplum"
author: "XRZ"
date: '2022-12-02'
output: html_document
---

# This R markdown script uploads the DX, PROC/HCPCS codes, and NDC codes needed for
# 5 Agencies - Wellness report.

# Codes have been pulled from Logic Wellness Measures v12
# (located in CDEXTRA$\XIAORUI\09-2022 5Agency Wellness\specs)

# and the actual spreadsheet to upload is located in the main folder
# (CDEXTRA$\XIAORUI\09-2022 5Agency Wellness\dx_codes.xlsx)

## 0.1 Load packages
```{r package-loading, warning = FALSE}
# Package installs/loading 

if (!require("pacman")) install.packages("pacman")
pacman::p_load(RPostgres, DBI, odbc, keyring, openxlsx, tidyverse, beepr, tictoc, here)

#packages I don't use anymore: rstudioapi

```


```{r connect-to-spcdedpwpvs1}	 
#Connect to Greenplum
tac <- dbConnect(RPostgres::Postgres(),
	 dbname = "uthealth",
	 user = "xrzhang",
	 password = key_get("Greenplum", "xrzhang"),
	 host = "greenplum01.corral.tacc.utexas.edu",
	 port = 5432)
```

```{r clear-environment}
# clears R environment except for DB connections
rm(list=setdiff(ls(), c("tac", "spc")))
```

```{r read-codes}
#Read files in
file = 'Q:/Users/XIAORUI/09-2022 5Agency Wellness/dx_codes.xlsx'

dx_codes = read.xlsx(file, "dx_codes")
cpt_codes = read.xlsx(file, "cpt_codes")
ndc_codes =  read.xlsx(file, "ndc")

#check max length to make sure our category names are all under 50 characters
max(nchar(dx_codes$category)) #18
max(nchar(cpt_codes$category)) #18

#create named vectors for specifying data types
dx_ft = c(dx="text", ICD="text", Category="text")
cpt_ft = c(cpt="text", ICD="text", Category="text")
ndc_ft = c(ndc="text")

```

```{r write-codes-to-server}
dbWriteTable(tac, SQL("dev.xz_5a_dx_codes"), dx_codes, overwrite = TRUE)
dbWriteTable(tac, SQL("dev.xz_5a_cpt_codes"), cpt_codes, overwrite = TRUE)
dbWriteTable(tac, SQL("dev.xz_5a_ndc_codes"), ndc_codes, overwrite = TRUE)
```


```{r disconnect-from-spcdedpwpvs1}	 
#Disconnect from SPCDEDPWPVS1
dbDisconnect(tac)
```





