vacuum analyze optum_zip.medical;
vacuum analyze optum_zip.confinement;
vacuum analyze optum_zip.diagnostic;
 --analyze optum_zip.facility_detail;
vacuum analyze optum_zip.lab_result;
vacuum analyze optum_zip.mbr_enroll;
vacuum analyze optum_zip.mbr_co_enroll;
vacuum analyze optum_zip.mbrwdeath;;
vacuum analyze optum_zip.procedure;
vacuum analyze optum_zip.provider;
vacuum analyze optum_zip.provider_bridge;
vacuum analyze optum_zip.rx;
