vacuum analyze optum_dod.medical;
vacuum analyze optum_dod.confinement;
vacuum analyze optum_dod.diagnostic;
 --analyze optum_dod.facility_detail;
vacuum analyze optum_dod.lab_result;
vacuum analyze optum_dod.mbr_enroll_r;
vacuum analyze optum_dod.mbr_co_enroll_r;
vacuum analyze optum_dod.mbrwdeath;;
vacuum analyze optum_dod.procedure;
vacuum analyze optum_dod.provider;
vacuum analyze optum_dod.provider_bridge;
vacuum analyze optum_dod.rx;
